### ISSUE TITLE
Pedido HTTP de exemplo falhando por não usar https.

### ISSUE THREAD

**Issue by NicolasCaous** [PostmonAPI/postmonapi.github.io#1]
Notei que o site que apresenta o projeto não está funcionando corretamente pois o pedido AJAX está sendo feito através do http. Como o site é obrigatoriamente servido em https, os navegadores atuais (como o chrome no meu caso) bloqueiam pedidos que consideram inseguros.

![image](https://user-images.githubusercontent.com/24411365/48957088-b8f66880-ef3d-11e8-9b80-45948490c087.png)

Como consertar: Alterar no arquivo ```javascripts/main.js``` linha 31 para o protocolo https. (Farei um pull request nesta issue).

**Comment by NicolasCaous** [comment]
Aguardado o merge do pull request para fechar a issue

**Comment by iurisilvio** [comment]
Eu fiz a correção disso faz tempo (cfb747ecccb19dd1f4a26c44634b288f60dd29cd, depois do seu PR), mas só percebi hoje que existia seu PR. :(
